language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zh-test-git/udemy-docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true zh-test-git/udemy-docker-react npm run test -- --coverage